### ISSUE TITLE
mezzio:handler:create \ CreateTemplate::getTemplateSuffixFromConfig()  must be of the type array, object given

### ISSUE THREAD

**Issue by PHPTCloud** [mezzio/mezzio-tooling#21]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 3.x

PHP 7.4

I tried create handler through cli command below. Its work okay, but I've got error of signature (see below). How to get rid of this problem or its a bug?

Command: 
```
$ php ./bin/laminas mezzio:handler:create App\\Handler\\SignInPageHandler
```

Console output:
```
Creating request handler App\Handler\SignInPageHandler...
Success!
- Created class App\Handler\SignInPageHandler, in file /<project_path>/src/App/Handler/SignInPageHandler.php
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Mezzio\Tooling\CreateHandler\CreateTemplate::getTemplateSuffixFromConfig() 
must be of the type array, object given, called in /<project_path>/vendor/mezzio/mezzio-tooling/src/CreateHandler/CreateTemplate.php on line 93 and 
defined in /<project_path>/vendor/mezzio/mezzio-tooling/src/CreateHandler/CreateTemplate.php:174

Stack trace:
#0 /<project_path>/vendor/mezzio/mezzio-tooling/src/CreateHandler/CreateTemplate.php(93): Mezzio\Tooling\CreateHandler\CreateTemplate->getTemplateSuffixFromConfig()
#1 /<project_path>/vendor/mezzio/mezzio-tooling/src/CreateHandler/CreateHandlerCommand.php(259): Mezzio\Tooling\CreateHandler\CreateTemplate->generateTemplate()
#2 /<project_path>/vendor/mezzio/mezzio-tooling/src/CreateHandler/CreateHandlerCommand.php(229): Mezzio\Tooling\CreateHandler\CreateHandlerCommand->generateTemplate()
#3 /<project_path>/vendor/mezzio/mezzio-tooling/src/CreateHandler/CreateTemplate.php on line 174
```

**Comment by weierophinney** [comment]
There is no v 3.x of mezzio-tooling; the latest version is 2.4.0. Use `composer show mezzio/mezzio-tooling` to determine the version you have installed locally.

I've tried the above with the 2.4.0 version, and get no errors.
